<?php
require_once('C:\wamp64\www\g4arena\configbdd.php');

session_start();
$id_event = $_GET['id_event'];

$queryEvent = $bdd->query("SELECT * FROM evenements WHERE id = " . $id_event);
$valeursEvent = $queryEvent->fetch();

$placesId = $bdd->query('SELECT * FROM places WHERE id_event = ' . $id_event . '');
$valeurs = $placesId->fetch();

if (isset($_POST['placeCreation'])) {
    $id_event = $_GET['id_event'];
    //CREATION PLACES ZONE VIP
    $placesVip = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event, rang, nplace) VALUES 
    (6, 1, "dispo", :idEvent, "A", 1),(6, 1, "dispo", :idEvent, "A", 2),(6, 1, "dispo", :idEvent, "A", 3),(6, 1, "dispo", :idEvent, "A", 4),(6, 1, "dispo", :idEvent, "A", 5),(6, 1, "dispo", :idEvent, "A", 6),(6, 1, "dispo", :idEvent, "A", 7),(6, 1, "dispo", :idEvent, "A", 8),(6, 1, "dispo", :idEvent, "A", 9),(6, 1, "dispo", :idEvent, "A", 10),(6, 1, "dispo", :idEvent, "A", 11),(6, 1, "dispo", :idEvent, "A", 12),(6, 1, "dispo", :idEvent, "A", 13),(6, 1, "dispo", :idEvent, "A", 14),(6, 1, "dispo", :idEvent, "A", 15),(6, 1, "dispo", :idEvent, "A", 16),(6, 1, "dispo", :idEvent, "A", 17),(6, 1, "dispo", :idEvent, "A", 18),(6, 1, "dispo", :idEvent, "A", 19),(6, 1, "dispo", :idEvent, "A", 20),(6, 1, "dispo", :idEvent, "A", 21),(6, 1, "dispo", :idEvent, "A", 22),(6, 1, "dispo", :idEvent, "A", 23),(6, 1, "dispo", :idEvent, "A", 24),(6, 1, "dispo", :idEvent, "A", 25),
    (6, 1, "dispo", :idEvent, "B", 1),(6, 1, "dispo", :idEvent, "B", 2),(6, 1, "dispo", :idEvent, "B", 3),(6, 1, "dispo", :idEvent, "B", 4),(6, 1, "dispo", :idEvent, "B", 5),(6, 1, "dispo", :idEvent, "B", 6),(6, 1, "dispo", :idEvent, "B", 7),(6, 1, "dispo", :idEvent, "B", 8),(6, 1, "dispo", :idEvent, "B", 9),(6, 1, "dispo", :idEvent, "B", 10),(6, 1, "dispo", :idEvent, "B", 11),(6, 1, "dispo", :idEvent, "B", 12),(6, 1, "dispo", :idEvent, "B", 13),(6, 1, "dispo", :idEvent, "B", 14),(6, 1, "dispo", :idEvent, "B", 15),(6, 1, "dispo", :idEvent, "B", 16),(6, 1, "dispo", :idEvent, "B", 17),(6, 1, "dispo", :idEvent, "B", 18),(6, 1, "dispo", :idEvent, "B", 19),(6, 1, "dispo", :idEvent, "B", 20),(6, 1, "dispo", :idEvent, "B", 21),(6, 1, "dispo", :idEvent, "B", 22),(6, 1, "dispo", :idEvent, "B", 23),(6, 1, "dispo", :idEvent, "B", 24),(6, 1, "dispo", :idEvent, "B", 25),
    (6, 1, "dispo", :idEvent, "C", 1),(6, 1, "dispo", :idEvent, "C", 2),(6, 1, "dispo", :idEvent, "C", 3),(6, 1, "dispo", :idEvent, "C", 4),(6, 1, "dispo", :idEvent, "C", 5),(6, 1, "dispo", :idEvent, "C", 6),(6, 1, "dispo", :idEvent, "C", 7),(6, 1, "dispo", :idEvent, "C", 8),(6, 1, "dispo", :idEvent, "C", 9),(6, 1, "dispo", :idEvent, "C", 10),(6, 1, "dispo", :idEvent, "C", 11),(6, 1, "dispo", :idEvent, "C", 12),(6, 1, "dispo", :idEvent, "C", 13),(6, 1, "dispo", :idEvent, "C", 14),(6, 1, "dispo", :idEvent, "C", 15),(6, 1, "dispo", :idEvent, "C", 16),(6, 1, "dispo", :idEvent, "C", 17),(6, 1, "dispo", :idEvent, "C", 18),(6, 1, "dispo", :idEvent, "C", 19),(6, 1, "dispo", :idEvent, "C", 20),(6, 1, "dispo", :idEvent, "C", 21),(6, 1, "dispo", :idEvent, "C", 22),(6, 1, "dispo", :idEvent, "C", 23),(6, 1, "dispo", :idEvent, "C", 24),(6, 1, "dispo", :idEvent, "C", 25),
    (6, 1, "dispo", :idEvent, "D", 1),(6, 1, "dispo", :idEvent, "D", 2),(6, 1, "dispo", :idEvent, "D", 3),(6, 1, "dispo", :idEvent, "D", 4),(6, 1, "dispo", :idEvent, "D", 5),(6, 1, "dispo", :idEvent, "D", 6),(6, 1, "dispo", :idEvent, "D", 7),(6, 1, "dispo", :idEvent, "D", 8),(6, 1, "dispo", :idEvent, "D", 9),(6, 1, "dispo", :idEvent, "D", 10),(6, 1, "dispo", :idEvent, "D", 11),(6, 1, "dispo", :idEvent, "D", 12),(6, 1, "dispo", :idEvent, "D", 13),(6, 1, "dispo", :idEvent, "D", 14),(6, 1, "dispo", :idEvent, "D", 15),(6, 1, "dispo", :idEvent, "D", 16),(6, 1, "dispo", :idEvent, "D", 17),(6, 1, "dispo", :idEvent, "D", 18),(6, 1, "dispo", :idEvent, "D", 19),(6, 1, "dispo", :idEvent, "D", 20),(6, 1, "dispo", :idEvent, "D", 21),(6, 1, "dispo", :idEvent, "D", 22),(6, 1, "dispo", :idEvent, "D", 23),(6, 1, "dispo", :idEvent, "D", 24),(6, 1, "dispo", :idEvent, "D", 25),
    (6, 1, "dispo", :idEvent, "E", 1),(6, 1, "dispo", :idEvent, "E", 2),(6, 1, "dispo", :idEvent, "E", 3),(6, 1, "dispo", :idEvent, "E", 4),(6, 1, "dispo", :idEvent, "E", 5),(6, 1, "dispo", :idEvent, "E", 6),(6, 1, "dispo", :idEvent, "E", 7),(6, 1, "dispo", :idEvent, "E", 8),(6, 1, "dispo", :idEvent, "E", 9),(6, 1, "dispo", :idEvent, "E", 10),(6, 1, "dispo", :idEvent, "E", 11),(6, 1, "dispo", :idEvent, "E", 12),(6, 1, "dispo", :idEvent, "E", 13),(6, 1, "dispo", :idEvent, "E", 14),(6, 1, "dispo", :idEvent, "E", 15),(6, 1, "dispo", :idEvent, "E", 16),(6, 1, "dispo", :idEvent, "E", 17),(6, 1, "dispo", :idEvent, "E", 18),(6, 1, "dispo", :idEvent, "E", 19),(6, 1, "dispo", :idEvent, "E", 20),(6, 1, "dispo", :idEvent, "E", 21),(6, 1, "dispo", :idEvent, "E", 22),(6, 1, "dispo", :idEvent, "E", 23),(6, 1, "dispo", :idEvent, "E", 24),(6, 1, "dispo", :idEvent, "E", 25),
    (6, 1, "dispo", :idEvent, "F", 1),(6, 1, "dispo", :idEvent, "F", 2),(6, 1, "dispo", :idEvent, "F", 3),(6, 1, "dispo", :idEvent, "F", 4),(6, 1, "dispo", :idEvent, "F", 5),(6, 1, "dispo", :idEvent, "F", 6),(6, 1, "dispo", :idEvent, "F", 7),(6, 1, "dispo", :idEvent, "F", 8),(6, 1, "dispo", :idEvent, "F", 9),(6, 1, "dispo", :idEvent, "F", 10),(6, 1, "dispo", :idEvent, "F", 11),(6, 1, "dispo", :idEvent, "F", 12),(6, 1, "dispo", :idEvent, "F", 13),(6, 1, "dispo", :idEvent, "F", 14),(6, 1, "dispo", :idEvent, "F", 15),(6, 1, "dispo", :idEvent, "F", 16),(6, 1, "dispo", :idEvent, "F", 17),(6, 1, "dispo", :idEvent, "F", 18),(6, 1, "dispo", :idEvent, "F", 19),(6, 1, "dispo", :idEvent, "F", 20),(6, 1, "dispo", :idEvent, "F", 21),(6, 1, "dispo", :idEvent, "F", 22),(6, 1, "dispo", :idEvent, "F", 23),(6, 1, "dispo", :idEvent, "F", 24),(6, 1, "dispo", :idEvent, "F", 25),
    (6, 1, "dispo", :idEvent, "G", 1),(6, 1, "dispo", :idEvent, "G", 2),(6, 1, "dispo", :idEvent, "G", 3),(6, 1, "dispo", :idEvent, "G", 4),(6, 1, "dispo", :idEvent, "G", 5),(6, 1, "dispo", :idEvent, "G", 6),(6, 1, "dispo", :idEvent, "G", 7),(6, 1, "dispo", :idEvent, "G", 8),(6, 1, "dispo", :idEvent, "G", 9),(6, 1, "dispo", :idEvent, "G", 10),(6, 1, "dispo", :idEvent, "G", 11),(6, 1, "dispo", :idEvent, "G", 12),(6, 1, "dispo", :idEvent, "G", 13),(6, 1, "dispo", :idEvent, "G", 14),(6, 1, "dispo", :idEvent, "G", 15),(6, 1, "dispo", :idEvent, "G", 16),(6, 1, "dispo", :idEvent, "G", 17),(6, 1, "dispo", :idEvent, "G", 18),(6, 1, "dispo", :idEvent, "G", 19),(6, 1, "dispo", :idEvent, "G", 20),(6, 1, "dispo", :idEvent, "G", 21),(6, 1, "dispo", :idEvent, "G", 22),(6, 1, "dispo", :idEvent, "G", 23),(6, 1, "dispo", :idEvent, "G", 24),(6, 1, "dispo", :idEvent, "G", 25),
    (6, 1, "dispo", :idEvent, "H", 1),(6, 1, "dispo", :idEvent, "H", 2),(6, 1, "dispo", :idEvent, "H", 3),(6, 1, "dispo", :idEvent, "H", 4),(6, 1, "dispo", :idEvent, "H", 5),(6, 1, "dispo", :idEvent, "H", 6),(6, 1, "dispo", :idEvent, "H", 7),(6, 1, "dispo", :idEvent, "H", 8),(6, 1, "dispo", :idEvent, "H", 9),(6, 1, "dispo", :idEvent, "H", 10),(6, 1, "dispo", :idEvent, "H", 11),(6, 1, "dispo", :idEvent, "H", 12),(6, 1, "dispo", :idEvent, "H", 13),(6, 1, "dispo", :idEvent, "H", 14),(6, 1, "dispo", :idEvent, "H", 15),(6, 1, "dispo", :idEvent, "H", 16),(6, 1, "dispo", :idEvent, "H", 17),(6, 1, "dispo", :idEvent, "H", 18),(6, 1, "dispo", :idEvent, "H", 19),(6, 1, "dispo", :idEvent, "H", 20),(6, 1, "dispo", :idEvent, "H", 21),(6, 1, "dispo", :idEvent, "H", 22),(6, 1, "dispo", :idEvent, "H", 23),(6, 1, "dispo", :idEvent, "H", 24),(6, 1, "dispo", :idEvent, "H", 25)
    ');
    $placesVip->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE 1
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event, rang, nplace) VALUES 
        (1, 1, "dispo", :idEvent, "A", 1),(1, 1, "dispo", :idEvent, "A", 2),(1, 1, "dispo", :idEvent, "A", 3),(1, 1, "dispo", :idEvent, "A", 4),(1, 1, "dispo", :idEvent, "A", 5),(1, 1, "dispo", :idEvent, "A", 6),(1, 1, "dispo", :idEvent, "A", 7),(1, 1, "dispo", :idEvent, "A", 8),(1, 1, "dispo", :idEvent, "A", 9),(1, 1, "dispo", :idEvent, "A", 10),(1, 1, "dispo", :idEvent, "A", 11),(1, 1, "dispo", :idEvent, "A", 12),(1, 1, "dispo", :idEvent, "A", 13),(1, 1, "dispo", :idEvent, "A", 14),(1, 1, "dispo", :idEvent, "A", 15),(1, 1, "dispo", :idEvent, "A", 16),(1, 1, "dispo", :idEvent, "A", 17),(1, 1, "dispo", :idEvent, "A", 18),(1, 1, "dispo", :idEvent, "A", 19),(1, 1, "dispo", :idEvent, "A", 20),(1, 1, "dispo", :idEvent, "A", 21),(1, 1, "dispo", :idEvent, "A", 22),(1, 1, "dispo", :idEvent, "A", 23),(1, 1, "dispo", :idEvent, "A", 24),(1, 1, "dispo", :idEvent, "A", 25),
        (1, 1, "dispo", :idEvent, "B", 1),(1, 1, "dispo", :idEvent, "B", 2),(1, 1, "dispo", :idEvent, "B", 3),(1, 1, "dispo", :idEvent, "B", 4),(1, 1, "dispo", :idEvent, "B", 5),(1, 1, "dispo", :idEvent, "B", 6),(1, 1, "dispo", :idEvent, "B", 7),(1, 1, "dispo", :idEvent, "B", 8),(1, 1, "dispo", :idEvent, "B", 9),(1, 1, "dispo", :idEvent, "B", 10),(1, 1, "dispo", :idEvent, "B", 11),(1, 1, "dispo", :idEvent, "B", 12),(1, 1, "dispo", :idEvent, "B", 13),(1, 1, "dispo", :idEvent, "B", 14),(1, 1, "dispo", :idEvent, "B", 15),(1, 1, "dispo", :idEvent, "B", 16),(1, 1, "dispo", :idEvent, "B", 17),(1, 1, "dispo", :idEvent, "B", 18),(1, 1, "dispo", :idEvent, "B", 19),(1, 1, "dispo", :idEvent, "B", 20),(1, 1, "dispo", :idEvent, "B", 21),(1, 1, "dispo", :idEvent, "B", 22),(1, 1, "dispo", :idEvent, "B", 23),(1, 1, "dispo", :idEvent, "B", 24),(1, 1, "dispo", :idEvent, "B", 25),
        (1, 1, "dispo", :idEvent, "C", 1),(1, 1, "dispo", :idEvent, "C", 2),(1, 1, "dispo", :idEvent, "C", 3),(1, 1, "dispo", :idEvent, "C", 4),(1, 1, "dispo", :idEvent, "C", 5),(1, 1, "dispo", :idEvent, "C", 6),(1, 1, "dispo", :idEvent, "C", 7),(1, 1, "dispo", :idEvent, "C", 8),(1, 1, "dispo", :idEvent, "C", 9),(1, 1, "dispo", :idEvent, "C", 10),(1, 1, "dispo", :idEvent, "C", 11),(1, 1, "dispo", :idEvent, "C", 12),(1, 1, "dispo", :idEvent, "C", 13),(1, 1, "dispo", :idEvent, "C", 14),(1, 1, "dispo", :idEvent, "C", 15),(1, 1, "dispo", :idEvent, "C", 16),(1, 1, "dispo", :idEvent, "C", 17),(1, 1, "dispo", :idEvent, "C", 18),(1, 1, "dispo", :idEvent, "C", 19),(1, 1, "dispo", :idEvent, "C", 20),(1, 1, "dispo", :idEvent, "C", 21),(1, 1, "dispo", :idEvent, "C", 22),(1, 1, "dispo", :idEvent, "C", 23),(1, 1, "dispo", :idEvent, "C", 24),(1, 1, "dispo", :idEvent, "C", 25),
        (1, 1, "dispo", :idEvent, "D", 1),(1, 1, "dispo", :idEvent, "D", 2),(1, 1, "dispo", :idEvent, "D", 3),(1, 1, "dispo", :idEvent, "D", 4),(1, 1, "dispo", :idEvent, "D", 5),(1, 1, "dispo", :idEvent, "D", 6),(1, 1, "dispo", :idEvent, "D", 7),(1, 1, "dispo", :idEvent, "D", 8),(1, 1, "dispo", :idEvent, "D", 9),(1, 1, "dispo", :idEvent, "D", 10),(1, 1, "dispo", :idEvent, "D", 11),(1, 1, "dispo", :idEvent, "D", 12),(1, 1, "dispo", :idEvent, "D", 13),(1, 1, "dispo", :idEvent, "D", 14),(1, 1, "dispo", :idEvent, "D", 15),(1, 1, "dispo", :idEvent, "D", 16),(1, 1, "dispo", :idEvent, "D", 17),(1, 1, "dispo", :idEvent, "D", 18),(1, 1, "dispo", :idEvent, "D", 19),(1, 1, "dispo", :idEvent, "D", 20),(1, 1, "dispo", :idEvent, "D", 21),(1, 1, "dispo", :idEvent, "D", 22),(1, 1, "dispo", :idEvent, "D", 23),(1, 1, "dispo", :idEvent, "D", 24),(1, 1, "dispo", :idEvent, "D", 25),
        (1, 1, "dispo", :idEvent, "E", 1),(1, 1, "dispo", :idEvent, "E", 2),(1, 1, "dispo", :idEvent, "E", 3),(1, 1, "dispo", :idEvent, "E", 4),(1, 1, "dispo", :idEvent, "E", 5),(1, 1, "dispo", :idEvent, "E", 6),(1, 1, "dispo", :idEvent, "E", 7),(1, 1, "dispo", :idEvent, "E", 8),(1, 1, "dispo", :idEvent, "E", 9),(1, 1, "dispo", :idEvent, "E", 10),(1, 1, "dispo", :idEvent, "E", 11),(1, 1, "dispo", :idEvent, "E", 12),(1, 1, "dispo", :idEvent, "E", 13),(1, 1, "dispo", :idEvent, "E", 14),(1, 1, "dispo", :idEvent, "E", 15),(1, 1, "dispo", :idEvent, "E", 16),(1, 1, "dispo", :idEvent, "E", 17),(1, 1, "dispo", :idEvent, "E", 18),(1, 1, "dispo", :idEvent, "E", 19),(1, 1, "dispo", :idEvent, "E", 20),(1, 1, "dispo", :idEvent, "E", 21),(1, 1, "dispo", :idEvent, "E", 22),(1, 1, "dispo", :idEvent, "E", 23),(1, 1, "dispo", :idEvent, "E", 24),(1, 1, "dispo", :idEvent, "E", 25),
        (1, 1, "dispo", :idEvent, "F", 1),(1, 1, "dispo", :idEvent, "F", 2),(1, 1, "dispo", :idEvent, "F", 3),(1, 1, "dispo", :idEvent, "F", 4),(1, 1, "dispo", :idEvent, "F", 5),(1, 1, "dispo", :idEvent, "F", 6),(1, 1, "dispo", :idEvent, "F", 7),(1, 1, "dispo", :idEvent, "F", 8),(1, 1, "dispo", :idEvent, "F", 9),(1, 1, "dispo", :idEvent, "F", 10),(1, 1, "dispo", :idEvent, "F", 11),(1, 1, "dispo", :idEvent, "F", 12),(1, 1, "dispo", :idEvent, "F", 13),(1, 1, "dispo", :idEvent, "F", 14),(1, 1, "dispo", :idEvent, "F", 15),(1, 1, "dispo", :idEvent, "F", 16),(1, 1, "dispo", :idEvent, "F", 17),(1, 1, "dispo", :idEvent, "F", 18),(1, 1, "dispo", :idEvent, "F", 19),(1, 1, "dispo", :idEvent, "F", 20),(1, 1, "dispo", :idEvent, "F", 21),(1, 1, "dispo", :idEvent, "F", 22),(1, 1, "dispo", :idEvent, "F", 23),(1, 1, "dispo", :idEvent, "F", 24),(1, 1, "dispo", :idEvent, "F", 25),
        (1, 1, "dispo", :idEvent, "G", 1),(1, 1, "dispo", :idEvent, "G", 2),(1, 1, "dispo", :idEvent, "G", 3),(1, 1, "dispo", :idEvent, "G", 4),(1, 1, "dispo", :idEvent, "G", 5),(1, 1, "dispo", :idEvent, "G", 6),(1, 1, "dispo", :idEvent, "G", 7),(1, 1, "dispo", :idEvent, "G", 8),(1, 1, "dispo", :idEvent, "G", 9),(1, 1, "dispo", :idEvent, "G", 10),(1, 1, "dispo", :idEvent, "G", 11),(1, 1, "dispo", :idEvent, "G", 12),(1, 1, "dispo", :idEvent, "G", 13),(1, 1, "dispo", :idEvent, "G", 14),(1, 1, "dispo", :idEvent, "G", 15),(1, 1, "dispo", :idEvent, "G", 16),(1, 1, "dispo", :idEvent, "G", 17),(1, 1, "dispo", :idEvent, "G", 18),(1, 1, "dispo", :idEvent, "G", 19),(1, 1, "dispo", :idEvent, "G", 20),(1, 1, "dispo", :idEvent, "G", 21),(1, 1, "dispo", :idEvent, "G", 22),(1, 1, "dispo", :idEvent, "G", 23),(1, 1, "dispo", :idEvent, "G", 24),(1, 1, "dispo", :idEvent, "G", 25),
        (1, 1, "dispo", :idEvent, "H", 1),(1, 1, "dispo", :idEvent, "H", 2),(1, 1, "dispo", :idEvent, "H", 3),(1, 1, "dispo", :idEvent, "H", 4),(1, 1, "dispo", :idEvent, "H", 5),(1, 1, "dispo", :idEvent, "H", 6),(1, 1, "dispo", :idEvent, "H", 7),(1, 1, "dispo", :idEvent, "H", 8),(1, 1, "dispo", :idEvent, "H", 9),(1, 1, "dispo", :idEvent, "H", 10),(1, 1, "dispo", :idEvent, "H", 11),(1, 1, "dispo", :idEvent, "H", 12),(1, 1, "dispo", :idEvent, "H", 13),(1, 1, "dispo", :idEvent, "H", 14),(1, 1, "dispo", :idEvent, "H", 15),(1, 1, "dispo", :idEvent, "H", 16),(1, 1, "dispo", :idEvent, "H", 17),(1, 1, "dispo", :idEvent, "H", 18),(1, 1, "dispo", :idEvent, "H", 19),(1, 1, "dispo", :idEvent, "H", 20),(1, 1, "dispo", :idEvent, "H", 21),(1, 1, "dispo", :idEvent, "H", 22),(1, 1, "dispo", :idEvent, "H", 23),(1, 1, "dispo", :idEvent, "H", 24),(1, 1, "dispo", :idEvent, "H", 25),
        (1, 1, "dispo", :idEvent, "I", 1),(1, 1, "dispo", :idEvent, "I", 2),(1, 1, "dispo", :idEvent, "I", 3),(1, 1, "dispo", :idEvent, "I", 4),(1, 1, "dispo", :idEvent, "I", 5),(1, 1, "dispo", :idEvent, "I", 6),(1, 1, "dispo", :idEvent, "I", 7),(1, 1, "dispo", :idEvent, "I", 8),(1, 1, "dispo", :idEvent, "I", 9),(1, 1, "dispo", :idEvent, "I", 10),(1, 1, "dispo", :idEvent, "I", 11),(1, 1, "dispo", :idEvent, "I", 12),(1, 1, "dispo", :idEvent, "I", 13),(1, 1, "dispo", :idEvent, "I", 14),(1, 1, "dispo", :idEvent, "I", 15),(1, 1, "dispo", :idEvent, "I", 16),(1, 1, "dispo", :idEvent, "I", 17),(1, 1, "dispo", :idEvent, "I", 18),(1, 1, "dispo", :idEvent, "I", 19),(1, 1, "dispo", :idEvent, "I", 20),(1, 1, "dispo", :idEvent, "I", 21),(1, 1, "dispo", :idEvent, "I", 22),(1, 1, "dispo", :idEvent, "I", 23),(1, 1, "dispo", :idEvent, "I", 24),(1, 1, "dispo", :idEvent, "I", 25),
        (1, 1, "dispo", :idEvent, "J", 1),(1, 1, "dispo", :idEvent, "J", 2),(1, 1, "dispo", :idEvent, "J", 3),(1, 1, "dispo", :idEvent, "J", 4),(1, 1, "dispo", :idEvent, "J", 5),(1, 1, "dispo", :idEvent, "J", 6),(1, 1, "dispo", :idEvent, "J", 7),(1, 1, "dispo", :idEvent, "J", 8),(1, 1, "dispo", :idEvent, "J", 9),(1, 1, "dispo", :idEvent, "J", 10),(1, 1, "dispo", :idEvent, "J", 11),(1, 1, "dispo", :idEvent, "J", 12),(1, 1, "dispo", :idEvent, "J", 13),(1, 1, "dispo", :idEvent, "J", 14),(1, 1, "dispo", :idEvent, "J", 15),(1, 1, "dispo", :idEvent, "J", 16),(1, 1, "dispo", :idEvent, "J", 17),(1, 1, "dispo", :idEvent, "J", 18),(1, 1, "dispo", :idEvent, "J", 19),(1, 1, "dispo", :idEvent, "J", 20),(1, 1, "dispo", :idEvent, "J", 21),(1, 1, "dispo", :idEvent, "J", 22),(1, 1, "dispo", :idEvent, "J", 23),(1, 1, "dispo", :idEvent, "J", 24),(1, 1, "dispo", :idEvent, "J", 25),
        (1, 1, "dispo", :idEvent, "K", 1),(1, 1, "dispo", :idEvent, "K", 2),(1, 1, "dispo", :idEvent, "K", 3),(1, 1, "dispo", :idEvent, "K", 4),(1, 1, "dispo", :idEvent, "K", 5),(1, 1, "dispo", :idEvent, "K", 6),(1, 1, "dispo", :idEvent, "K", 7),(1, 1, "dispo", :idEvent, "K", 8),(1, 1, "dispo", :idEvent, "K", 9),(1, 1, "dispo", :idEvent, "K", 10),(1, 1, "dispo", :idEvent, "K", 11),(1, 1, "dispo", :idEvent, "K", 12),(1, 1, "dispo", :idEvent, "K", 13),(1, 1, "dispo", :idEvent, "K", 14),(1, 1, "dispo", :idEvent, "K", 15),(1, 1, "dispo", :idEvent, "K", 16),(1, 1, "dispo", :idEvent, "K", 17),(1, 1, "dispo", :idEvent, "K", 18),(1, 1, "dispo", :idEvent, "K", 19),(1, 1, "dispo", :idEvent, "K", 20),(1, 1, "dispo", :idEvent, "K", 21),(1, 1, "dispo", :idEvent, "K", 22),(1, 1, "dispo", :idEvent, "K", 23),(1, 1, "dispo", :idEvent, "K", 24),(1, 1, "dispo", :idEvent, "K", 25),   
        (1, 1, "dispo", :idEvent, "L", 1),(1, 1, "dispo", :idEvent, "L", 2),(1, 1, "dispo", :idEvent, "L", 3),(1, 1, "dispo", :idEvent, "L", 4),(1, 1, "dispo", :idEvent, "L", 5),(1, 1, "dispo", :idEvent, "L", 6),(1, 1, "dispo", :idEvent, "L", 7),(1, 1, "dispo", :idEvent, "L", 8),(1, 1, "dispo", :idEvent, "L", 9),(1, 1, "dispo", :idEvent, "L", 10),(1, 1, "dispo", :idEvent, "L", 11),(1, 1, "dispo", :idEvent, "L", 12),(1, 1, "dispo", :idEvent, "L", 13),(1, 1, "dispo", :idEvent, "L", 14),(1, 1, "dispo", :idEvent, "L", 15),(1, 1, "dispo", :idEvent, "L", 16),(1, 1, "dispo", :idEvent, "L", 17),(1, 1, "dispo", :idEvent, "L", 18),(1, 1, "dispo", :idEvent, "L", 19),(1, 1, "dispo", :idEvent, "L", 20),(1, 1, "dispo", :idEvent, "L", 21),(1, 1, "dispo", :idEvent, "L", 22),(1, 1, "dispo", :idEvent, "L", 23),(1, 1, "dispo", :idEvent, "L", 24),(1, 1, "dispo", :idEvent, "L", 25)
        ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE 2
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event, rang, nplace) VALUES 
    (2, 1, "dispo", :idEvent, "A", 1),(2, 1, "dispo", :idEvent, "A", 2),(2, 1, "dispo", :idEvent, "A", 3),(2, 1, "dispo", :idEvent, "A", 4),(2, 1, "dispo", :idEvent, "A", 5),(2, 1, "dispo", :idEvent, "A", 6),(2, 1, "dispo", :idEvent, "A", 7),(2, 1, "dispo", :idEvent, "A", 8),(2, 1, "dispo", :idEvent, "A", 9),(2, 1, "dispo", :idEvent, "A", 10),(2, 1, "dispo", :idEvent, "A", 11),(2, 1, "dispo", :idEvent, "A", 12),(2, 1, "dispo", :idEvent, "A", 13),(2, 1, "dispo", :idEvent, "A", 14),(2, 1, "dispo", :idEvent, "A", 15),(2, 1, "dispo", :idEvent, "A", 16),(2, 1, "dispo", :idEvent, "A", 17),(2, 1, "dispo", :idEvent, "A", 18),(2, 1, "dispo", :idEvent, "A", 19),(2, 1, "dispo", :idEvent, "A", 20),(2, 1, "dispo", :idEvent, "A", 21),(2, 1, "dispo", :idEvent, "A", 22),(2, 1, "dispo", :idEvent, "A", 23),(2, 1, "dispo", :idEvent, "A", 24),(2, 1, "dispo", :idEvent, "A", 25),
    (2, 1, "dispo", :idEvent, "B", 1),(2, 1, "dispo", :idEvent, "B", 2),(2, 1, "dispo", :idEvent, "B", 3),(2, 1, "dispo", :idEvent, "B", 4),(2, 1, "dispo", :idEvent, "B", 5),(2, 1, "dispo", :idEvent, "B", 6),(2, 1, "dispo", :idEvent, "B", 7),(2, 1, "dispo", :idEvent, "B", 8),(2, 1, "dispo", :idEvent, "B", 9),(2, 1, "dispo", :idEvent, "B", 10),(2, 1, "dispo", :idEvent, "B", 11),(2, 1, "dispo", :idEvent, "B", 12),(2, 1, "dispo", :idEvent, "B", 13),(2, 1, "dispo", :idEvent, "B", 14),(2, 1, "dispo", :idEvent, "B", 15),(2, 1, "dispo", :idEvent, "B", 16),(2, 1, "dispo", :idEvent, "B", 17),(2, 1, "dispo", :idEvent, "B", 18),(2, 1, "dispo", :idEvent, "B", 19),(2, 1, "dispo", :idEvent, "B", 20),(2, 1, "dispo", :idEvent, "B", 21),(2, 1, "dispo", :idEvent, "B", 22),(2, 1, "dispo", :idEvent, "B", 23),(2, 1, "dispo", :idEvent, "B", 24),(2, 1, "dispo", :idEvent, "B", 25),
    (2, 1, "dispo", :idEvent, "C", 1),(2, 1, "dispo", :idEvent, "C", 2),(2, 1, "dispo", :idEvent, "C", 3),(2, 1, "dispo", :idEvent, "C", 4),(2, 1, "dispo", :idEvent, "C", 5),(2, 1, "dispo", :idEvent, "C", 6),(2, 1, "dispo", :idEvent, "C", 7),(2, 1, "dispo", :idEvent, "C", 8),(2, 1, "dispo", :idEvent, "C", 9),(2, 1, "dispo", :idEvent, "C", 10),(2, 1, "dispo", :idEvent, "C", 11),(2, 1, "dispo", :idEvent, "C", 12),(2, 1, "dispo", :idEvent, "C", 13),(2, 1, "dispo", :idEvent, "C", 14),(2, 1, "dispo", :idEvent, "C", 15),(2, 1, "dispo", :idEvent, "C", 16),(2, 1, "dispo", :idEvent, "C", 17),(2, 1, "dispo", :idEvent, "C", 18),(2, 1, "dispo", :idEvent, "C", 19),(2, 1, "dispo", :idEvent, "C", 20),(2, 1, "dispo", :idEvent, "C", 21),(2, 1, "dispo", :idEvent, "C", 22),(2, 1, "dispo", :idEvent, "C", 23),(2, 1, "dispo", :idEvent, "C", 24),(2, 1, "dispo", :idEvent, "C", 25),
    (2, 1, "dispo", :idEvent, "D", 1),(2, 1, "dispo", :idEvent, "D", 2),(2, 1, "dispo", :idEvent, "D", 3),(2, 1, "dispo", :idEvent, "D", 4),(2, 1, "dispo", :idEvent, "D", 5),(2, 1, "dispo", :idEvent, "D", 6),(2, 1, "dispo", :idEvent, "D", 7),(2, 1, "dispo", :idEvent, "D", 8),(2, 1, "dispo", :idEvent, "D", 9),(2, 1, "dispo", :idEvent, "D", 10),(2, 1, "dispo", :idEvent, "D", 11),(2, 1, "dispo", :idEvent, "D", 12),(2, 1, "dispo", :idEvent, "D", 13),(2, 1, "dispo", :idEvent, "D", 14),(2, 1, "dispo", :idEvent, "D", 15),(2, 1, "dispo", :idEvent, "D", 16),(2, 1, "dispo", :idEvent, "D", 17),(2, 1, "dispo", :idEvent, "D", 18),(2, 1, "dispo", :idEvent, "D", 19),(2, 1, "dispo", :idEvent, "D", 20),(2, 1, "dispo", :idEvent, "D", 21),(2, 1, "dispo", :idEvent, "D", 22),(2, 1, "dispo", :idEvent, "D", 23),(2, 1, "dispo", :idEvent, "D", 24),(2, 1, "dispo", :idEvent, "D", 25),
    (2, 1, "dispo", :idEvent, "E", 1),(2, 1, "dispo", :idEvent, "E", 2),(2, 1, "dispo", :idEvent, "E", 3),(2, 1, "dispo", :idEvent, "E", 4),(2, 1, "dispo", :idEvent, "E", 5),(2, 1, "dispo", :idEvent, "E", 6),(2, 1, "dispo", :idEvent, "E", 7),(2, 1, "dispo", :idEvent, "E", 8),(2, 1, "dispo", :idEvent, "E", 9),(2, 1, "dispo", :idEvent, "E", 10),(2, 1, "dispo", :idEvent, "E", 11),(2, 1, "dispo", :idEvent, "E", 12),(2, 1, "dispo", :idEvent, "E", 13),(2, 1, "dispo", :idEvent, "E", 14),(2, 1, "dispo", :idEvent, "E", 15),(2, 1, "dispo", :idEvent, "E", 16),(2, 1, "dispo", :idEvent, "E", 17),(2, 1, "dispo", :idEvent, "E", 18),(2, 1, "dispo", :idEvent, "E", 19),(2, 1, "dispo", :idEvent, "E", 20),(2, 1, "dispo", :idEvent, "E", 21),(2, 1, "dispo", :idEvent, "E", 22),(2, 1, "dispo", :idEvent, "E", 23),(2, 1, "dispo", :idEvent, "E", 24),(2, 1, "dispo", :idEvent, "E", 25),
    (2, 1, "dispo", :idEvent, "F", 1),(2, 1, "dispo", :idEvent, "F", 2),(2, 1, "dispo", :idEvent, "F", 3),(2, 1, "dispo", :idEvent, "F", 4),(2, 1, "dispo", :idEvent, "F", 5),(2, 1, "dispo", :idEvent, "F", 6),(2, 1, "dispo", :idEvent, "F", 7),(2, 1, "dispo", :idEvent, "F", 8),(2, 1, "dispo", :idEvent, "F", 9),(2, 1, "dispo", :idEvent, "F", 10),(2, 1, "dispo", :idEvent, "F", 11),(2, 1, "dispo", :idEvent, "F", 12),(2, 1, "dispo", :idEvent, "F", 13),(2, 1, "dispo", :idEvent, "F", 14),(2, 1, "dispo", :idEvent, "F", 15),(2, 1, "dispo", :idEvent, "F", 16),(2, 1, "dispo", :idEvent, "F", 17),(2, 1, "dispo", :idEvent, "F", 18),(2, 1, "dispo", :idEvent, "F", 19),(2, 1, "dispo", :idEvent, "F", 20),(2, 1, "dispo", :idEvent, "F", 21),(2, 1, "dispo", :idEvent, "F", 22),(2, 1, "dispo", :idEvent, "F", 23),(2, 1, "dispo", :idEvent, "F", 24),(2, 1, "dispo", :idEvent, "F", 25),
    (2, 1, "dispo", :idEvent, "G", 1),(2, 1, "dispo", :idEvent, "G", 2),(2, 1, "dispo", :idEvent, "G", 3),(2, 1, "dispo", :idEvent, "G", 4),(2, 1, "dispo", :idEvent, "G", 5),(2, 1, "dispo", :idEvent, "G", 6),(2, 1, "dispo", :idEvent, "G", 7),(2, 1, "dispo", :idEvent, "G", 8),(2, 1, "dispo", :idEvent, "G", 9),(2, 1, "dispo", :idEvent, "G", 10),(2, 1, "dispo", :idEvent, "G", 11),(2, 1, "dispo", :idEvent, "G", 12),(2, 1, "dispo", :idEvent, "G", 13),(2, 1, "dispo", :idEvent, "G", 14),(2, 1, "dispo", :idEvent, "G", 15),(2, 1, "dispo", :idEvent, "G", 16),(2, 1, "dispo", :idEvent, "G", 17),(2, 1, "dispo", :idEvent, "G", 18),(2, 1, "dispo", :idEvent, "G", 19),(2, 1, "dispo", :idEvent, "G", 20),(2, 1, "dispo", :idEvent, "G", 21),(2, 1, "dispo", :idEvent, "G", 22),(2, 1, "dispo", :idEvent, "G", 23),(2, 1, "dispo", :idEvent, "G", 24),(2, 1, "dispo", :idEvent, "G", 25),
    (2, 1, "dispo", :idEvent, "H", 1),(2, 1, "dispo", :idEvent, "H", 2),(2, 1, "dispo", :idEvent, "H", 3),(2, 1, "dispo", :idEvent, "H", 4),(2, 1, "dispo", :idEvent, "H", 5),(2, 1, "dispo", :idEvent, "H", 6),(2, 1, "dispo", :idEvent, "H", 7),(2, 1, "dispo", :idEvent, "H", 8),(2, 1, "dispo", :idEvent, "H", 9),(2, 1, "dispo", :idEvent, "H", 10),(2, 1, "dispo", :idEvent, "H", 11),(2, 1, "dispo", :idEvent, "H", 12),(2, 1, "dispo", :idEvent, "H", 13),(2, 1, "dispo", :idEvent, "H", 14),(2, 1, "dispo", :idEvent, "H", 15),(2, 1, "dispo", :idEvent, "H", 16),(2, 1, "dispo", :idEvent, "H", 17),(2, 1, "dispo", :idEvent, "H", 18),(2, 1, "dispo", :idEvent, "H", 19),(2, 1, "dispo", :idEvent, "H", 20),(2, 1, "dispo", :idEvent, "H", 21),(2, 1, "dispo", :idEvent, "H", 22),(2, 1, "dispo", :idEvent, "H", 23),(2, 1, "dispo", :idEvent, "H", 24),(2, 1, "dispo", :idEvent, "H", 25),
    (2, 1, "dispo", :idEvent, "I", 1),(2, 1, "dispo", :idEvent, "I", 2),(2, 1, "dispo", :idEvent, "I", 3),(2, 1, "dispo", :idEvent, "I", 4),(2, 1, "dispo", :idEvent, "I", 5),(2, 1, "dispo", :idEvent, "I", 6),(2, 1, "dispo", :idEvent, "I", 7),(2, 1, "dispo", :idEvent, "I", 8),(2, 1, "dispo", :idEvent, "I", 9),(2, 1, "dispo", :idEvent, "I", 10),(2, 1, "dispo", :idEvent, "I", 11),(2, 1, "dispo", :idEvent, "I", 12),(2, 1, "dispo", :idEvent, "I", 13),(2, 1, "dispo", :idEvent, "I", 14),(2, 1, "dispo", :idEvent, "I", 15),(2, 1, "dispo", :idEvent, "I", 16),(2, 1, "dispo", :idEvent, "I", 17),(2, 1, "dispo", :idEvent, "I", 18),(2, 1, "dispo", :idEvent, "I", 19),(2, 1, "dispo", :idEvent, "I", 20),(2, 1, "dispo", :idEvent, "I", 21),(2, 1, "dispo", :idEvent, "I", 22),(2, 1, "dispo", :idEvent, "I", 23),(2, 1, "dispo", :idEvent, "I", 24),(2, 1, "dispo", :idEvent, "I", 25),
    (2, 1, "dispo", :idEvent, "J", 1),(2, 1, "dispo", :idEvent, "J", 2),(2, 1, "dispo", :idEvent, "J", 3),(2, 1, "dispo", :idEvent, "J", 4),(2, 1, "dispo", :idEvent, "J", 5),(2, 1, "dispo", :idEvent, "J", 6),(2, 1, "dispo", :idEvent, "J", 7),(2, 1, "dispo", :idEvent, "J", 8),(2, 1, "dispo", :idEvent, "J", 9),(2, 1, "dispo", :idEvent, "J", 10),(2, 1, "dispo", :idEvent, "J", 11),(2, 1, "dispo", :idEvent, "J", 12),(2, 1, "dispo", :idEvent, "J", 13),(2, 1, "dispo", :idEvent, "J", 14),(2, 1, "dispo", :idEvent, "J", 15),(2, 1, "dispo", :idEvent, "J", 16),(2, 1, "dispo", :idEvent, "J", 17),(2, 1, "dispo", :idEvent, "J", 18),(2, 1, "dispo", :idEvent, "J", 19),(2, 1, "dispo", :idEvent, "J", 20),(2, 1, "dispo", :idEvent, "J", 21),(2, 1, "dispo", :idEvent, "J", 22),(2, 1, "dispo", :idEvent, "J", 23),(2, 1, "dispo", :idEvent, "J", 24),(2, 1, "dispo", :idEvent, "J", 25),
    (2, 1, "dispo", :idEvent, "K", 1),(2, 1, "dispo", :idEvent, "K", 2),(2, 1, "dispo", :idEvent, "K", 3),(2, 1, "dispo", :idEvent, "K", 4),(2, 1, "dispo", :idEvent, "K", 5),(2, 1, "dispo", :idEvent, "K", 6),(2, 1, "dispo", :idEvent, "K", 7),(2, 1, "dispo", :idEvent, "K", 8),(2, 1, "dispo", :idEvent, "K", 9),(2, 1, "dispo", :idEvent, "K", 10),(2, 1, "dispo", :idEvent, "K", 11),(2, 1, "dispo", :idEvent, "K", 12),(2, 1, "dispo", :idEvent, "K", 13),(2, 1, "dispo", :idEvent, "K", 14),(2, 1, "dispo", :idEvent, "K", 15),(2, 1, "dispo", :idEvent, "K", 16),(2, 1, "dispo", :idEvent, "K", 17),(2, 1, "dispo", :idEvent, "K", 18),(2, 1, "dispo", :idEvent, "K", 19),(2, 1, "dispo", :idEvent, "K", 20),(2, 1, "dispo", :idEvent, "K", 21),(2, 1, "dispo", :idEvent, "K", 22),(2, 1, "dispo", :idEvent, "K", 23),(2, 1, "dispo", :idEvent, "K", 24),(2, 1, "dispo", :idEvent, "K", 25),
    (2, 1, "dispo", :idEvent, "L", 1),(2, 1, "dispo", :idEvent, "L", 2),(2, 1, "dispo", :idEvent, "L", 3),(2, 1, "dispo", :idEvent, "L", 4),(2, 1, "dispo", :idEvent, "L", 5),(2, 1, "dispo", :idEvent, "L", 6),(2, 1, "dispo", :idEvent, "L", 7),(2, 1, "dispo", :idEvent, "L", 8),(2, 1, "dispo", :idEvent, "L", 9),(2, 1, "dispo", :idEvent, "L", 10),(2, 1, "dispo", :idEvent, "L", 11),(2, 1, "dispo", :idEvent, "L", 12),(2, 1, "dispo", :idEvent, "L", 13),(2, 1, "dispo", :idEvent, "L", 14),(2, 1, "dispo", :idEvent, "L", 15),(2, 1, "dispo", :idEvent, "L", 16),(2, 1, "dispo", :idEvent, "L", 17),(2, 1, "dispo", :idEvent, "L", 18),(2, 1, "dispo", :idEvent, "L", 19),(2, 1, "dispo", :idEvent, "L", 20),(2, 1, "dispo", :idEvent, "L", 21),(2, 1, "dispo", :idEvent, "L", 22),(2, 1, "dispo", :idEvent, "L", 23),(2, 1, "dispo", :idEvent, "L", 24),(2, 1, "dispo", :idEvent, "L", 25)
    ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE 3
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event, rang, nplace) VALUES 
        (3, 1, "dispo", :idEvent, "A", 1),(3, 1, "dispo", :idEvent, "A", 2),(3, 1, "dispo", :idEvent, "A", 3),(3, 1, "dispo", :idEvent, "A", 4),(3, 1, "dispo", :idEvent, "A", 5),(3, 1, "dispo", :idEvent, "A", 6),(3, 1, "dispo", :idEvent, "A", 7),(3, 1, "dispo", :idEvent, "A", 8),(3, 1, "dispo", :idEvent, "A", 9),(3, 1, "dispo", :idEvent, "A", 10),(3, 1, "dispo", :idEvent, "A", 11),(3, 1, "dispo", :idEvent, "A", 12),(3, 1, "dispo", :idEvent, "A", 13),(3, 1, "dispo", :idEvent, "A", 14),(3, 1, "dispo", :idEvent, "A", 15),(3, 1, "dispo", :idEvent, "A", 16),(3, 1, "dispo", :idEvent, "A", 17),(3, 1, "dispo", :idEvent, "A", 18),(3, 1, "dispo", :idEvent, "A", 19),(3, 1, "dispo", :idEvent, "A", 20),(3, 1, "dispo", :idEvent, "A", 21),(3, 1, "dispo", :idEvent, "A", 22),(3, 1, "dispo", :idEvent, "A", 23),(3, 1, "dispo", :idEvent, "A", 24),(3, 1, "dispo", :idEvent, "A", 25),
        (3, 1, "dispo", :idEvent, "B", 1),(3, 1, "dispo", :idEvent, "B", 2),(3, 1, "dispo", :idEvent, "B", 3),(3, 1, "dispo", :idEvent, "B", 4),(3, 1, "dispo", :idEvent, "B", 5),(3, 1, "dispo", :idEvent, "B", 6),(3, 1, "dispo", :idEvent, "B", 7),(3, 1, "dispo", :idEvent, "B", 8),(3, 1, "dispo", :idEvent, "B", 9),(3, 1, "dispo", :idEvent, "B", 10),(3, 1, "dispo", :idEvent, "B", 11),(3, 1, "dispo", :idEvent, "B", 12),(3, 1, "dispo", :idEvent, "B", 13),(3, 1, "dispo", :idEvent, "B", 14),(3, 1, "dispo", :idEvent, "B", 15),(3, 1, "dispo", :idEvent, "B", 16),(3, 1, "dispo", :idEvent, "B", 17),(3, 1, "dispo", :idEvent, "B", 18),(3, 1, "dispo", :idEvent, "B", 19),(3, 1, "dispo", :idEvent, "B", 20),(3, 1, "dispo", :idEvent, "B", 21),(3, 1, "dispo", :idEvent, "B", 22),(3, 1, "dispo", :idEvent, "B", 23),(3, 1, "dispo", :idEvent, "B", 24),(3, 1, "dispo", :idEvent, "B", 25),
        (3, 1, "dispo", :idEvent, "C", 1),(3, 1, "dispo", :idEvent, "C", 2),(3, 1, "dispo", :idEvent, "C", 3),(3, 1, "dispo", :idEvent, "C", 4),(3, 1, "dispo", :idEvent, "C", 5),(3, 1, "dispo", :idEvent, "C", 6),(3, 1, "dispo", :idEvent, "C", 7),(3, 1, "dispo", :idEvent, "C", 8),(3, 1, "dispo", :idEvent, "C", 9),(3, 1, "dispo", :idEvent, "C", 10),(3, 1, "dispo", :idEvent, "C", 11),(3, 1, "dispo", :idEvent, "C", 12),(3, 1, "dispo", :idEvent, "C", 13),(3, 1, "dispo", :idEvent, "C", 14),(3, 1, "dispo", :idEvent, "C", 15),(3, 1, "dispo", :idEvent, "C", 16),(3, 1, "dispo", :idEvent, "C", 17),(3, 1, "dispo", :idEvent, "C", 18),(3, 1, "dispo", :idEvent, "C", 19),(3, 1, "dispo", :idEvent, "C", 20),(3, 1, "dispo", :idEvent, "C", 21),(3, 1, "dispo", :idEvent, "C", 22),(3, 1, "dispo", :idEvent, "C", 23),(3, 1, "dispo", :idEvent, "C", 24),(3, 1, "dispo", :idEvent, "C", 25),
        (3, 1, "dispo", :idEvent, "D", 1),(3, 1, "dispo", :idEvent, "D", 2),(3, 1, "dispo", :idEvent, "D", 3),(3, 1, "dispo", :idEvent, "D", 4),(3, 1, "dispo", :idEvent, "D", 5),(3, 1, "dispo", :idEvent, "D", 6),(3, 1, "dispo", :idEvent, "D", 7),(3, 1, "dispo", :idEvent, "D", 8),(3, 1, "dispo", :idEvent, "D", 9),(3, 1, "dispo", :idEvent, "D", 10),(3, 1, "dispo", :idEvent, "D", 11),(3, 1, "dispo", :idEvent, "D", 12),(3, 1, "dispo", :idEvent, "D", 13),(3, 1, "dispo", :idEvent, "D", 14),(3, 1, "dispo", :idEvent, "D", 15),(3, 1, "dispo", :idEvent, "D", 16),(3, 1, "dispo", :idEvent, "D", 17),(3, 1, "dispo", :idEvent, "D", 18),(3, 1, "dispo", :idEvent, "D", 19),(3, 1, "dispo", :idEvent, "D", 20),(3, 1, "dispo", :idEvent, "D", 21),(3, 1, "dispo", :idEvent, "D", 22),(3, 1, "dispo", :idEvent, "D", 23),(3, 1, "dispo", :idEvent, "D", 24),(3, 1, "dispo", :idEvent, "D", 25),
        (3, 1, "dispo", :idEvent, "E", 1),(3, 1, "dispo", :idEvent, "E", 2),(3, 1, "dispo", :idEvent, "E", 3),(3, 1, "dispo", :idEvent, "E", 4),(3, 1, "dispo", :idEvent, "E", 5),(3, 1, "dispo", :idEvent, "E", 6),(3, 1, "dispo", :idEvent, "E", 7),(3, 1, "dispo", :idEvent, "E", 8),(3, 1, "dispo", :idEvent, "E", 9),(3, 1, "dispo", :idEvent, "E", 10),(3, 1, "dispo", :idEvent, "E", 11),(3, 1, "dispo", :idEvent, "E", 12),(3, 1, "dispo", :idEvent, "E", 13),(3, 1, "dispo", :idEvent, "E", 14),(3, 1, "dispo", :idEvent, "E", 15),(3, 1, "dispo", :idEvent, "E", 16),(3, 1, "dispo", :idEvent, "E", 17),(3, 1, "dispo", :idEvent, "E", 18),(3, 1, "dispo", :idEvent, "E", 19),(3, 1, "dispo", :idEvent, "E", 20),(3, 1, "dispo", :idEvent, "E", 21),(3, 1, "dispo", :idEvent, "E", 22),(3, 1, "dispo", :idEvent, "E", 23),(3, 1, "dispo", :idEvent, "E", 24),(3, 1, "dispo", :idEvent, "E", 25),
        (3, 1, "dispo", :idEvent, "F", 1),(3, 1, "dispo", :idEvent, "F", 2),(3, 1, "dispo", :idEvent, "F", 3),(3, 1, "dispo", :idEvent, "F", 4),(3, 1, "dispo", :idEvent, "F", 5),(3, 1, "dispo", :idEvent, "F", 6),(3, 1, "dispo", :idEvent, "F", 7),(3, 1, "dispo", :idEvent, "F", 8),(3, 1, "dispo", :idEvent, "F", 9),(3, 1, "dispo", :idEvent, "F", 10),(3, 1, "dispo", :idEvent, "F", 11),(3, 1, "dispo", :idEvent, "F", 12),(3, 1, "dispo", :idEvent, "F", 13),(3, 1, "dispo", :idEvent, "F", 14),(3, 1, "dispo", :idEvent, "F", 15),(3, 1, "dispo", :idEvent, "F", 16),(3, 1, "dispo", :idEvent, "F", 17),(3, 1, "dispo", :idEvent, "F", 18),(3, 1, "dispo", :idEvent, "F", 19),(3, 1, "dispo", :idEvent, "F", 20),(3, 1, "dispo", :idEvent, "F", 21),(3, 1, "dispo", :idEvent, "F", 22),(3, 1, "dispo", :idEvent, "F", 23),(3, 1, "dispo", :idEvent, "F", 24),(3, 1, "dispo", :idEvent, "F", 25),
        (3, 1, "dispo", :idEvent, "G", 1),(3, 1, "dispo", :idEvent, "G", 2),(3, 1, "dispo", :idEvent, "G", 3),(3, 1, "dispo", :idEvent, "G", 4),(3, 1, "dispo", :idEvent, "G", 5),(3, 1, "dispo", :idEvent, "G", 6),(3, 1, "dispo", :idEvent, "G", 7),(3, 1, "dispo", :idEvent, "G", 8),(3, 1, "dispo", :idEvent, "G", 9),(3, 1, "dispo", :idEvent, "G", 10),(3, 1, "dispo", :idEvent, "G", 11),(3, 1, "dispo", :idEvent, "G", 12),(3, 1, "dispo", :idEvent, "G", 13),(3, 1, "dispo", :idEvent, "G", 14),(3, 1, "dispo", :idEvent, "G", 15),(3, 1, "dispo", :idEvent, "G", 16),(3, 1, "dispo", :idEvent, "G", 17),(3, 1, "dispo", :idEvent, "G", 18),(3, 1, "dispo", :idEvent, "G", 19),(3, 1, "dispo", :idEvent, "G", 20),(3, 1, "dispo", :idEvent, "G", 21),(3, 1, "dispo", :idEvent, "G", 22),(3, 1, "dispo", :idEvent, "G", 23),(3, 1, "dispo", :idEvent, "G", 24),(3, 1, "dispo", :idEvent, "G", 25),
        (3, 1, "dispo", :idEvent, "H", 1),(3, 1, "dispo", :idEvent, "H", 2),(3, 1, "dispo", :idEvent, "H", 3),(3, 1, "dispo", :idEvent, "H", 4),(3, 1, "dispo", :idEvent, "H", 5),(3, 1, "dispo", :idEvent, "H", 6),(3, 1, "dispo", :idEvent, "H", 7),(3, 1, "dispo", :idEvent, "H", 8),(3, 1, "dispo", :idEvent, "H", 9),(3, 1, "dispo", :idEvent, "H", 10),(3, 1, "dispo", :idEvent, "H", 11),(3, 1, "dispo", :idEvent, "H", 12),(3, 1, "dispo", :idEvent, "H", 13),(3, 1, "dispo", :idEvent, "H", 14),(3, 1, "dispo", :idEvent, "H", 15),(3, 1, "dispo", :idEvent, "H", 16),(3, 1, "dispo", :idEvent, "H", 17),(3, 1, "dispo", :idEvent, "H", 18),(3, 1, "dispo", :idEvent, "H", 19),(3, 1, "dispo", :idEvent, "H", 20),(3, 1, "dispo", :idEvent, "H", 21),(3, 1, "dispo", :idEvent, "H", 22),(3, 1, "dispo", :idEvent, "H", 23),(3, 1, "dispo", :idEvent, "H", 24),(3, 1, "dispo", :idEvent, "H", 25),
        (3, 1, "dispo", :idEvent, "I", 1),(3, 1, "dispo", :idEvent, "I", 2),(3, 1, "dispo", :idEvent, "I", 3),(3, 1, "dispo", :idEvent, "I", 4),(3, 1, "dispo", :idEvent, "I", 5),(3, 1, "dispo", :idEvent, "I", 6),(3, 1, "dispo", :idEvent, "I", 7),(3, 1, "dispo", :idEvent, "I", 8),(3, 1, "dispo", :idEvent, "I", 9),(3, 1, "dispo", :idEvent, "I", 10),(3, 1, "dispo", :idEvent, "I", 11),(3, 1, "dispo", :idEvent, "I", 12),(3, 1, "dispo", :idEvent, "I", 13),(3, 1, "dispo", :idEvent, "I", 14),(3, 1, "dispo", :idEvent, "I", 15),(3, 1, "dispo", :idEvent, "I", 16),(3, 1, "dispo", :idEvent, "I", 17),(3, 1, "dispo", :idEvent, "I", 18),(3, 1, "dispo", :idEvent, "I", 19),(3, 1, "dispo", :idEvent, "I", 20),(3, 1, "dispo", :idEvent, "I", 21),(3, 1, "dispo", :idEvent, "I", 22),(3, 1, "dispo", :idEvent, "I", 23),(3, 1, "dispo", :idEvent, "I", 24),(3, 1, "dispo", :idEvent, "I", 25),
        (3, 1, "dispo", :idEvent, "J", 1),(3, 1, "dispo", :idEvent, "J", 2),(3, 1, "dispo", :idEvent, "J", 3),(3, 1, "dispo", :idEvent, "J", 4),(3, 1, "dispo", :idEvent, "J", 5),(3, 1, "dispo", :idEvent, "J", 6),(3, 1, "dispo", :idEvent, "J", 7),(3, 1, "dispo", :idEvent, "J", 8),(3, 1, "dispo", :idEvent, "J", 9),(3, 1, "dispo", :idEvent, "J", 10),(3, 1, "dispo", :idEvent, "J", 11),(3, 1, "dispo", :idEvent, "J", 12),(3, 1, "dispo", :idEvent, "J", 13),(3, 1, "dispo", :idEvent, "J", 14),(3, 1, "dispo", :idEvent, "J", 15),(3, 1, "dispo", :idEvent, "J", 16),(3, 1, "dispo", :idEvent, "J", 17),(3, 1, "dispo", :idEvent, "J", 18),(3, 1, "dispo", :idEvent, "J", 19),(3, 1, "dispo", :idEvent, "J", 20),(3, 1, "dispo", :idEvent, "J", 21),(3, 1, "dispo", :idEvent, "J", 22),(3, 1, "dispo", :idEvent, "J", 23),(3, 1, "dispo", :idEvent, "J", 24),(3, 1, "dispo", :idEvent, "J", 25)
        ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE 4
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event, rang, nplace) VALUES 
    (4, 1, "dispo", :idEvent, "A", 1),(4, 1, "dispo", :idEvent, "A", 2),(4, 1, "dispo", :idEvent, "A", 3),(4, 1, "dispo", :idEvent, "A", 4),(4, 1, "dispo", :idEvent, "A", 5),(4, 1, "dispo", :idEvent, "A", 6),(4, 1, "dispo", :idEvent, "A", 7),(4, 1, "dispo", :idEvent, "A", 8),(4, 1, "dispo", :idEvent, "A", 9),(4, 1, "dispo", :idEvent, "A", 10),(4, 1, "dispo", :idEvent, "A", 11),(4, 1, "dispo", :idEvent, "A", 12),(4, 1, "dispo", :idEvent, "A", 13),(4, 1, "dispo", :idEvent, "A", 14),(4, 1, "dispo", :idEvent, "A", 15),(4, 1, "dispo", :idEvent, "A", 16),(4, 1, "dispo", :idEvent, "A", 17),(4, 1, "dispo", :idEvent, "A", 18),(4, 1, "dispo", :idEvent, "A", 19),(4, 1, "dispo", :idEvent, "A", 20),(4, 1, "dispo", :idEvent, "A", 21),(4, 1, "dispo", :idEvent, "A", 22),(4, 1, "dispo", :idEvent, "A", 23),(4, 1, "dispo", :idEvent, "A", 24),(4, 1, "dispo", :idEvent, "A", 25),
    (4, 1, "dispo", :idEvent, "B", 1),(4, 1, "dispo", :idEvent, "B", 2),(4, 1, "dispo", :idEvent, "B", 3),(4, 1, "dispo", :idEvent, "B", 4),(4, 1, "dispo", :idEvent, "B", 5),(4, 1, "dispo", :idEvent, "B", 6),(4, 1, "dispo", :idEvent, "B", 7),(4, 1, "dispo", :idEvent, "B", 8),(4, 1, "dispo", :idEvent, "B", 9),(4, 1, "dispo", :idEvent, "B", 10),(4, 1, "dispo", :idEvent, "B", 11),(4, 1, "dispo", :idEvent, "B", 12),(4, 1, "dispo", :idEvent, "B", 13),(4, 1, "dispo", :idEvent, "B", 14),(4, 1, "dispo", :idEvent, "B", 15),(4, 1, "dispo", :idEvent, "B", 16),(4, 1, "dispo", :idEvent, "B", 17),(4, 1, "dispo", :idEvent, "B", 18),(4, 1, "dispo", :idEvent, "B", 19),(4, 1, "dispo", :idEvent, "B", 20),(4, 1, "dispo", :idEvent, "B", 21),(4, 1, "dispo", :idEvent, "B", 22),(4, 1, "dispo", :idEvent, "B", 23),(4, 1, "dispo", :idEvent, "B", 24),(4, 1, "dispo", :idEvent, "B", 25),
    (4, 1, "dispo", :idEvent, "C", 1),(4, 1, "dispo", :idEvent, "C", 2),(4, 1, "dispo", :idEvent, "C", 3),(4, 1, "dispo", :idEvent, "C", 4),(4, 1, "dispo", :idEvent, "C", 5),(4, 1, "dispo", :idEvent, "C", 6),(4, 1, "dispo", :idEvent, "C", 7),(4, 1, "dispo", :idEvent, "C", 8),(4, 1, "dispo", :idEvent, "C", 9),(4, 1, "dispo", :idEvent, "C", 10),(4, 1, "dispo", :idEvent, "C", 11),(4, 1, "dispo", :idEvent, "C", 12),(4, 1, "dispo", :idEvent, "C", 13),(4, 1, "dispo", :idEvent, "C", 14),(4, 1, "dispo", :idEvent, "C", 15),(4, 1, "dispo", :idEvent, "C", 16),(4, 1, "dispo", :idEvent, "C", 17),(4, 1, "dispo", :idEvent, "C", 18),(4, 1, "dispo", :idEvent, "C", 19),(4, 1, "dispo", :idEvent, "C", 20),(4, 1, "dispo", :idEvent, "C", 21),(4, 1, "dispo", :idEvent, "C", 22),(4, 1, "dispo", :idEvent, "C", 23),(4, 1, "dispo", :idEvent, "C", 24),(4, 1, "dispo", :idEvent, "C", 25),
    (4, 1, "dispo", :idEvent, "D", 1),(4, 1, "dispo", :idEvent, "D", 2),(4, 1, "dispo", :idEvent, "D", 3),(4, 1, "dispo", :idEvent, "D", 4),(4, 1, "dispo", :idEvent, "D", 5),(4, 1, "dispo", :idEvent, "D", 6),(4, 1, "dispo", :idEvent, "D", 7),(4, 1, "dispo", :idEvent, "D", 8),(4, 1, "dispo", :idEvent, "D", 9),(4, 1, "dispo", :idEvent, "D", 10),(4, 1, "dispo", :idEvent, "D", 11),(4, 1, "dispo", :idEvent, "D", 12),(4, 1, "dispo", :idEvent, "D", 13),(4, 1, "dispo", :idEvent, "D", 14),(4, 1, "dispo", :idEvent, "D", 15),(4, 1, "dispo", :idEvent, "D", 16),(4, 1, "dispo", :idEvent, "D", 17),(4, 1, "dispo", :idEvent, "D", 18),(4, 1, "dispo", :idEvent, "D", 19),(4, 1, "dispo", :idEvent, "D", 20),(4, 1, "dispo", :idEvent, "D", 21),(4, 1, "dispo", :idEvent, "D", 22),(4, 1, "dispo", :idEvent, "D", 23),(4, 1, "dispo", :idEvent, "D", 24),(4, 1, "dispo", :idEvent, "D", 25),
    (4, 1, "dispo", :idEvent, "E", 1),(4, 1, "dispo", :idEvent, "E", 2),(4, 1, "dispo", :idEvent, "E", 3),(4, 1, "dispo", :idEvent, "E", 4),(4, 1, "dispo", :idEvent, "E", 5),(4, 1, "dispo", :idEvent, "E", 6),(4, 1, "dispo", :idEvent, "E", 7),(4, 1, "dispo", :idEvent, "E", 8),(4, 1, "dispo", :idEvent, "E", 9),(4, 1, "dispo", :idEvent, "E", 10),(4, 1, "dispo", :idEvent, "E", 11),(4, 1, "dispo", :idEvent, "E", 12),(4, 1, "dispo", :idEvent, "E", 13),(4, 1, "dispo", :idEvent, "E", 14),(4, 1, "dispo", :idEvent, "E", 15),(4, 1, "dispo", :idEvent, "E", 16),(4, 1, "dispo", :idEvent, "E", 17),(4, 1, "dispo", :idEvent, "E", 18),(4, 1, "dispo", :idEvent, "E", 19),(4, 1, "dispo", :idEvent, "E", 20),(4, 1, "dispo", :idEvent, "E", 21),(4, 1, "dispo", :idEvent, "E", 22),(4, 1, "dispo", :idEvent, "E", 23),(4, 1, "dispo", :idEvent, "E", 24),(4, 1, "dispo", :idEvent, "E", 25),
    (4, 1, "dispo", :idEvent, "F", 1),(4, 1, "dispo", :idEvent, "F", 2),(4, 1, "dispo", :idEvent, "F", 3),(4, 1, "dispo", :idEvent, "F", 4),(4, 1, "dispo", :idEvent, "F", 5),(4, 1, "dispo", :idEvent, "F", 6),(4, 1, "dispo", :idEvent, "F", 7),(4, 1, "dispo", :idEvent, "F", 8),(4, 1, "dispo", :idEvent, "F", 9),(4, 1, "dispo", :idEvent, "F", 10),(4, 1, "dispo", :idEvent, "F", 11),(4, 1, "dispo", :idEvent, "F", 12),(4, 1, "dispo", :idEvent, "F", 13),(4, 1, "dispo", :idEvent, "F", 14),(4, 1, "dispo", :idEvent, "F", 15),(4, 1, "dispo", :idEvent, "F", 16),(4, 1, "dispo", :idEvent, "F", 17),(4, 1, "dispo", :idEvent, "F", 18),(4, 1, "dispo", :idEvent, "F", 19),(4, 1, "dispo", :idEvent, "F", 20),(4, 1, "dispo", :idEvent, "F", 21),(4, 1, "dispo", :idEvent, "F", 22),(4, 1, "dispo", :idEvent, "F", 23),(4, 1, "dispo", :idEvent, "F", 24),(4, 1, "dispo", :idEvent, "F", 25),
    (4, 1, "dispo", :idEvent, "G", 1),(4, 1, "dispo", :idEvent, "G", 2),(4, 1, "dispo", :idEvent, "G", 3),(4, 1, "dispo", :idEvent, "G", 4),(4, 1, "dispo", :idEvent, "G", 5),(4, 1, "dispo", :idEvent, "G", 6),(4, 1, "dispo", :idEvent, "G", 7),(4, 1, "dispo", :idEvent, "G", 8),(4, 1, "dispo", :idEvent, "G", 9),(4, 1, "dispo", :idEvent, "G", 10),(4, 1, "dispo", :idEvent, "G", 11),(4, 1, "dispo", :idEvent, "G", 12),(4, 1, "dispo", :idEvent, "G", 13),(4, 1, "dispo", :idEvent, "G", 14),(4, 1, "dispo", :idEvent, "G", 15),(4, 1, "dispo", :idEvent, "G", 16),(4, 1, "dispo", :idEvent, "G", 17),(4, 1, "dispo", :idEvent, "G", 18),(4, 1, "dispo", :idEvent, "G", 19),(4, 1, "dispo", :idEvent, "G", 20),(4, 1, "dispo", :idEvent, "G", 21),(4, 1, "dispo", :idEvent, "G", 22),(4, 1, "dispo", :idEvent, "G", 23),(4, 1, "dispo", :idEvent, "G", 24),(4, 1, "dispo", :idEvent, "G", 25),
    (4, 1, "dispo", :idEvent, "H", 1),(4, 1, "dispo", :idEvent, "H", 2),(4, 1, "dispo", :idEvent, "H", 3),(4, 1, "dispo", :idEvent, "H", 4),(4, 1, "dispo", :idEvent, "H", 5),(4, 1, "dispo", :idEvent, "H", 6),(4, 1, "dispo", :idEvent, "H", 7),(4, 1, "dispo", :idEvent, "H", 8),(4, 1, "dispo", :idEvent, "H", 9),(4, 1, "dispo", :idEvent, "H", 10),(4, 1, "dispo", :idEvent, "H", 11),(4, 1, "dispo", :idEvent, "H", 12),(4, 1, "dispo", :idEvent, "H", 13),(4, 1, "dispo", :idEvent, "H", 14),(4, 1, "dispo", :idEvent, "H", 15),(4, 1, "dispo", :idEvent, "H", 16),(4, 1, "dispo", :idEvent, "H", 17),(4, 1, "dispo", :idEvent, "H", 18),(4, 1, "dispo", :idEvent, "H", 19),(4, 1, "dispo", :idEvent, "H", 20),(4, 1, "dispo", :idEvent, "H", 21),(4, 1, "dispo", :idEvent, "H", 22),(4, 1, "dispo", :idEvent, "H", 23),(4, 1, "dispo", :idEvent, "H", 24),(4, 1, "dispo", :idEvent, "H", 25),
    (4, 1, "dispo", :idEvent, "I", 1),(4, 1, "dispo", :idEvent, "I", 2),(4, 1, "dispo", :idEvent, "I", 3),(4, 1, "dispo", :idEvent, "I", 4),(4, 1, "dispo", :idEvent, "I", 5),(4, 1, "dispo", :idEvent, "I", 6),(4, 1, "dispo", :idEvent, "I", 7),(4, 1, "dispo", :idEvent, "I", 8),(4, 1, "dispo", :idEvent, "I", 9),(4, 1, "dispo", :idEvent, "I", 10),(4, 1, "dispo", :idEvent, "I", 11),(4, 1, "dispo", :idEvent, "I", 12),(4, 1, "dispo", :idEvent, "I", 13),(4, 1, "dispo", :idEvent, "I", 14),(4, 1, "dispo", :idEvent, "I", 15),(4, 1, "dispo", :idEvent, "I", 16),(4, 1, "dispo", :idEvent, "I", 17),(4, 1, "dispo", :idEvent, "I", 18),(4, 1, "dispo", :idEvent, "I", 19),(4, 1, "dispo", :idEvent, "I", 20),(4, 1, "dispo", :idEvent, "I", 21),(4, 1, "dispo", :idEvent, "I", 22),(4, 1, "dispo", :idEvent, "I", 23),(4, 1, "dispo", :idEvent, "I", 24),(4, 1, "dispo", :idEvent, "I", 25),
    (4, 1, "dispo", :idEvent, "J", 1),(4, 1, "dispo", :idEvent, "J", 2),(4, 1, "dispo", :idEvent, "J", 3),(4, 1, "dispo", :idEvent, "J", 4),(4, 1, "dispo", :idEvent, "J", 5),(4, 1, "dispo", :idEvent, "J", 6),(4, 1, "dispo", :idEvent, "J", 7),(4, 1, "dispo", :idEvent, "J", 8),(4, 1, "dispo", :idEvent, "J", 9),(4, 1, "dispo", :idEvent, "J", 10),(4, 1, "dispo", :idEvent, "J", 11),(4, 1, "dispo", :idEvent, "J", 12),(4, 1, "dispo", :idEvent, "J", 13),(4, 1, "dispo", :idEvent, "J", 14),(4, 1, "dispo", :idEvent, "J", 15),(4, 1, "dispo", :idEvent, "J", 16),(4, 1, "dispo", :idEvent, "J", 17),(4, 1, "dispo", :idEvent, "J", 18),(4, 1, "dispo", :idEvent, "J", 19),(4, 1, "dispo", :idEvent, "J", 20),(4, 1, "dispo", :idEvent, "J", 21),(4, 1, "dispo", :idEvent, "J", 22),(4, 1, "dispo", :idEvent, "J", 23),(4, 1, "dispo", :idEvent, "J", 24),(4, 1, "dispo", :idEvent, "J", 25)
    ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE FOSEE x 250 
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event) VALUES 
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent)
        ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE FOSEE x 250 
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event) VALUES 
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent)
    ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE FOSEE x 250 
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event) VALUES 
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent)
        ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE FOSEE x 250 
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event) VALUES 
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
    (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent)
    ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    //CREATION PLACES ZONE FOSEE x 200 
    $placesZone1 = $bdd->prepare('INSERT INTO places (id_zone, id_user, statut, id_event) VALUES 
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),
        (5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent),(5,1,"dispo",:idEvent)
        ');
    $placesZone1->execute(array(
        'idEvent' => $id_event
    ));

    header('Location:/ressources/views/infoEvenement.php?id=' . $valeursEvent['id'] . '');
}
